version: '3.7'

services:
  api-gateway:
    image: karthiks7678/estockmarketappv1-api-gateway:0.0.2-SNAPSHOT
    ports:
     - "8765:8765"
    restart: always
    networks:
     - est-ntwrk
    depends_on:
     - naming-server
    environment:
      eureka.client.serviceurl.defaultZone: http://naming-server:8761/eureka
      
  comp-info-serv:
    image: karthiks7678/estockmarketappv1-company-info-services:0.0.2-SNAPSHOT
    ports:
     - "8180:8180"
    restart: always
    networks:
     - est-ntwrk
    depends_on:
     - naming-server
    environment:
      eureka.client.serviceurl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_ZIPKIN_RABBITMQ_QUEUE: zipkin

  stock-info-ser:
    image: karthiks7678/estockmarketappv1-stock-info-services:0.0.2-SNAPSHOT
    ports:
     - "8280:8280"
    restart: always
    networks:
     - est-ntwrk
    depends_on:
     - estockmarketapp-naming-server
     - mysql
     - rabbitmq
    environment:
      eureka.client.serviceurl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_ZIPKIN_RABBITMQ_QUEUE: zipkin

  estock-mes-ser:
    image: karthiks7678/estockmarketappv1-message-queue-services:0.0.3-SNAPSHOT
    ports:
     - "8380:8380"
    restart: always  
    networks:
     - est-ntwrk
    depends_on:
     - naming-server
     - rabbitmq
    environment:
      eureka.client.serviceurl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_ZIPKIN_RABBITMQ_QUEUE: zipkin

  info-reader:
    image: karthiks7678/estockmarketappv1-estock-market-info-reader:0.0.2-SNAPSHOT
    ports:
     - "8382:8382"
    restart: always  
    networks:
     - est-ntwrk
    depends_on:
     - naming-server
    environment:
      eureka.client.serviceurl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_ZIPKIN_RABBITMQ_QUEUE: zipkin

  api-sec:
    image: karthiks7678/estockmarketappv1-security-service:0.0.2-SNAPSHOT
    ports:
     - "8100:8100"
    restart: always
    networks:
     - est-ntwrk
    depends_on:
     - naming-server
     - mysql
    environment:
      eureka.client.serviceurl.defaultZone: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_ZIPKIN_RABBITMQ_QUEUE: zipkin

  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
     - "9411:9411"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
     - naming-server
     - rabbitmq
    networks:
     - est-ntwrk

  rabbitmq:
    image: rabbitmq:3.8.12-management
    ports:
     - "5672:5672"
     - "15672:15672"
    restart: always
    depends_on:
     - naming-server
    networks:
     - est-ntwrk

  naming-server:
    image: karthiks7678/estockmarketappv1-netflix-eureka-naming-server:0.0.1-SNAPSHOT
    ports:
     - "8761:8761"
    restart: always
    networks:
     - est-ntwrk

networks:
  est-ntwrk: